config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: [:new, :edit, :destroy] do
    member do
      get :confirm
    end
  end
  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users
    resources :employees

    root to: "users#index"
  end
  resources :posts do
    member do
      get :approve
      get :reject
    end
  end
  devise_for :users, skip: [:registrations]
  root to: 'static#homepage'

end

app/views/shared/_admin_dashboard_tab.html.erb
<li><%= link_to "Admin Dashboard", admin_root_path %></li>

app/views/shared/_alerts.html.erb
<%= js add_gritter(flash[:notice], title: "Overtime App Notification", sticky: false) %>
<%= js add_gritter(flash[:alert], title: "Overtime App Notification", sticky: false) %>
<%= js add_gritter(flash[:error], title: "Overtime App Notification", sticky: false) %>

app/views/shared/_audit_log_tab.html.erb
<li class ="<%= active?(audit_logs_path) %>"><%= link_to "Audit Logs", audit_logs_path, id: "new_post_from_nav" %></li>

app/views/shared/_nav.html.erb
<nav class="custom-nav navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Time Tracker", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <% if current_user %>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class ="<%= active?(root_path) %>"><%= link_to " ", root_path, class: "glyphicon glyphicon-home" %></li>
          <%= render 'shared/audit_log_tab' if policy(AuditLog).index? %>
          <%= render 'shared/post_dropdown' if employee? %>
          <%= render 'shared/post_index_tab' if admin? %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-cog"><span class="caret"></span></a>
              <ul class="dropdown-menu">
                <%= render 'shared/admin_dashboard_tab' if admin? %>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          </ul>
      </div>
    <% end %>
  </div>
</nav>

app/views/shared/_post_dropdown.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Overtime Entries<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li class ="<%= active?(posts_path) %>"><%= link_to "List of Entries", posts_path %></li>
    <li role="separator" class="divider"></li>
    <li class ="<%= active?(new_post_path) %>"><%= link_to "Add New Entry", new_post_path, id: "new_post_from_nav" %></li>
  </ul>
</li>

app/views/shared/_post_index_tab.html.erb
<li class ="<%= active?(posts_path) %>"><%= link_to "List of Time Entries", posts_path %></li>

app/views/shared/_title.html.erb
<h3></h3>
<hr />